### ISSUE TITLE
Remove the text in the fields under CVFragment, keeping the required hints.

### ISSUE THREAD

**Issue by adrishyantee** [DSCKGEC/Resumie#10]
The section for Professional Experience has fields that are filled with texts. Those texts should be replaced with hints. Filling the text option should be given if the user wants to write something there.

This small bug needs to be solved first before moving to issue #7

**Comment by SugatoBagchi** [comment]
Hi, 

I would like to work on this issue. Can you elaborate a little more so that I can get a complete idea about it?

**Comment by adrishyantee** [comment]
Has this issue been started to work upon? @SugatoBagchi

**Comment by SugatoBagchi** [comment]
@adrishyantee I cannot fix the issue. I request you to unassign me from this and I hope to contribute on some other issue in future.

**Comment by prince02765** [comment]
Hello, Can I pick up this issue I already Found an Error for this issue.

**Comment by adrishyantee** [comment]
@prince02765 I assigned you!

**Comment by adrishyantee** [comment]
@prince02765 Can you go through the issue once again and check it for the repo. I think the text fields are not removed. Please validate this. Even after adding fields, The previous items remain the same.
