### ISSUE TITLE
Floating button to add or delete items in the CVFragment - needed

### ISSUE THREAD

**Issue by adrishyantee** [DSCKGEC/Resumie#11]
There has to be an option for the user to add or delete items they need in the recycler view under the CVFragment.

[How to add a floating button in the bottom right?](https://developer.android.com/guide/topics/ui/floating-action-button) and make it [functional](https://www.journaldev.com/10318/android-floating-action-button-example-tutorial)

Go through [this](http://www.techsolpoint.com/how-to-add-remove-and-update-items-in-android-recyclerview-android-studio.html) to add a new item in the RecyclerView.

**Comment by prince02765** [comment]
I want to add this functionality. Can I work on this issue?

**Comment by adrishyantee** [comment]
Sure! Go Ahead.

**Comment by mahmood199** [comment]
Can i work on this if the issue is still unsolved?

**Comment by adrishyantee** [comment]
@prince02765 Can you give an update on your progress?

**Comment by prince02765** [comment]
Yes, I started till now I added a floating button with Alert Dialog. Now, just need to implement Insert Method in the recycler view.

**Comment by adrishyantee** [comment]
Alright, go ahead!

**Comment by prince02765** [comment]
![20210527](https://user-images.githubusercontent.com/69643676/119929730-ae4c3c80-bf9b-11eb-856c-50d6cb3bde58.jpg)

I can not see the Dialog box button Text as per the above picture. Can I Edit In themes.xml colorPrimary?  It is White so I can not see the button's text color.

**Comment by adrishyantee** [comment]
Surely you can!
