### ISSUE TITLE
Disable keyboard pop-up for each Fragment

### ISSUE THREAD

**Issue by adrishyantee** [DSCKGEC/Resumie#13]
The first view for the fragments is an EditText and so we need to hide the keyboard popup for it.

[How to disable the keypad popup when on edit text?](https://stackoverflow.com/questions/10611833/how-to-disable-keypad-popup-when-on-edittext)

The issue is quite simple and easy but must be applied to all the required fragments.

**Comment by mahmood199** [comment]
Would like to work on this.

**Comment by adrishyantee** [comment]
So, I check a few other devices as well, and some of them have this keyboard pop-up enabled. I was thinking of writing this one line in the Manifest file:

```
  <activity android:name=".MainActivity" 
             android:windowSoftInputMode="stateHidden" />
```

Can you add this line and check if that is working on other devices smoothly or not.
