### ISSUE TITLE
Use Sharedpreferences to save the state of items in CV Fragment.

### ISSUE THREAD

**Issue by adrishyantee** [DSCKGEC/Resumie#25]
The items under CV Fragment need to be saved during editing, using shared preferences. So that when the app is opened again the items don't get deleted.

You can save the Array list to the Shared Preferences once the item is added and then remove it from there when deleted. 
The saved ArrayList should be displayed when the fragment is the viewed after the app opens.

[Use Sharedpreferences to save custom objects](https://www.geeksforgeeks.org/how-to-save-arraylist-to-sharedpreferences-in-android/)
You can make a save floating button above add floating button.

**Comment by mahmood199** [comment]
Would like to work on this issue.

**Comment by mahmood199** [comment]
Done
