### ISSUE TITLE
Make the PDF design for the resume to be created.

### ISSUE THREAD

**Issue by adrishyantee** [DSCKGEC/Resumie#5]
- We want a clean and simple design of the PDF finally created with the data available at this moment. 
- Use of different but minimum font styles and colors will be appreciated.
- You need to check the PDF Activity for the changes to make.
- Go through [this](https://developer.android.com/reference/android/graphics/pdf/PdfDocument) for more.

**Comment by mahmood199** [comment]
Would like to work on this issue.

**Comment by adrishyantee** [comment]
This issue is still open for others to work upon.
