### ISSUE TITLE
Views in activity_pdf.xml needs to be placed properly

### ISSUE THREAD

**Issue by adrishyantee** [DSCKGEC/Resumie#6]
- Go through the activity_pdf.xml file and try to align the data in such a way that it is properly visible to the users.
- You need to have basic knowledge of the different views and their attributes.

**Comment by mahmood199** [comment]
Please assign this issue to me.
Also can I use custom drawables for better look of the text fields?

**Comment by adrishyantee** [comment]
This issue is taken by someone else as well. Please go through the discord channel of resumie and discuss the ideas. For now, I will assign this to both of you.

**Comment by chirag828049** [comment]
I was actually working on this.

**Comment by adrishyantee** [comment]
@chirag828049 I will merge your pull request and keep this issue open for further modifications.
