### ISSUE TITLE
Add a feature to add and change the image of the user profile icon/avatar

### ISSUE THREAD

**Issue by adrishyantee** [DSCKGEC/Resumie#9]
The user profile icon in the top left does not have the feature for adding an avatar image as per the user and changing it later.

The way it should work:
1.  When the icon is clicked, display a pop-up asking user to add an image or cancel.
2.  Button to Add Image.
3. Uploading the image from the gallery.
4. Button for updating the image.
5. Showing the updated avatar until a further change is done.

How can you do it?
1. [How to pick an image from the gallery?](https://www.viralpatel.net/pick-image-from-galary-android-app/)
2. [How to store images using SharedPreferences?](https://stackoverflow.com/questions/8586242/how-to-store-images-using-sharedpreference-in-android)

You can try out the above ones.

3. [Most Preferable is using Glide or Picasso Library to do this](https://medium.com/android-news/avatarview-custom-implementation-of-imageview-4bcf0714d09d)

**Comment by mahmood199** [comment]
Would like to work on this one

Apart from image selection and cancel can we add one more option?
To display the current profile image

**Comment by adrishyantee** [comment]
> Would like to work on this one
> 
> Apart from image selection and cancel can we add one more option?
> To display the current profile image -- would do this in a new issue

That's a great idea!

**Comment by mahmood199** [comment]
Created pull request
